Feature michałt post /auth/register customer support agent
Reservant-inc/reservant-backend pull request #1
Opened 2024-03-09 13:26 UTC by DummSmartass

2024-03-09 14:40 UTC, Mroxny commented on Api/Services/UserService.cs
> +    public async Task<Result<User>> RegisterCustomerSupportAgentAsync(RegisterCustomerSupportAgentRequest request)
UserService powinien przypisywać role uzytkownikowi

2024-03-09 14:41 UTC, Mroxny requested changes
UserService powinien przypisywać role uzytkownikowi

2024-03-10 16:09 UTC, linewelder approved these changes

2024-03-10 16:15 UTC, Mroxny approved these changes

2024-03-10 16:18 UTC, merged