[FEATURE] Get Restaurants
Reservant-inc/reservant-backend pull request #109
Opened 2024-06-02 18:07 UTC by skrapi2011

Endpoint searches for restaurants in a given radius (currently max 20km) and returns List<NearRestaurantVM> containing sorted qualified restaurants
+ distanceFrom is in meters - (15564.503 = 15,564km)
+ Added simple validation (radius cannot be less than 0, bigger than limit)

2024-06-02 19:08 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wyszukiwanie restauracji](https://trello.com/c/7zZsV9ye/86-wyszukiwanie-restauracji)

2024-06-04 15:57 UTC, linewelder requested changes

2024-06-18 11:38 UTC, skrapi2011 commented on Api/Services/RestaurantService.cs
> +                var distance = R * c; // Distance in meters
Tak myślałem, tylko nie wiedziałem gdzie miałbym umieścić taką funkcję (czy na dole w service, czy gdzieś w jakiejś klasie utils)

2024-06-18 12:26 UTC, skrapi2011 commented on Api/Models/Dtos/Restaurant/NearRestaurantVM.cs
> +    public required double distanceFrom { get; init; }
Poprawione

2024-06-18 12:28 UTC, skrapi2011 commented on Api/Models/Dtos/Restaurant/NearRestaurantVM.cs
> +    public required bool IsVerified { get; init; }
Zmienione

2024-06-18 20:18 UTC, merged