Added GET auth/is-unique controller
Reservant-inc/reservant-backend pull request #14
Opened 2024-03-27 21:45 UTC by DummSmartass

2024-03-28 15:00 UTC, linewelder requested changes

2024-03-28 15:32 UTC, linewelder commented on Api/Controllers/AuthController.cs
> +    public async Task<ActionResult> isUnique(String mail)
metody nazywamy dużą literą

2024-03-28 15:32 UTC, linewelder commented on Api/Services/UserService.cs
> +    public async Task<bool> isUniqueAsync(string mail)
metody nazywamy dużą literą

2024-04-11 10:01 UTC, Mroxny approved these changes

2024-04-15 00:34 UTC, merged