Feature michal w add future visit
Reservant-inc/reservant-backend pull request #143
Opened 2024-07-22 14:18 UTC by skrapi2011

Added add-future-endpoint in Debug controller that creates example visit with orders

2024-07-22 14:22 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[CHORE] Końcówka do tworzenia przykładowej wizyty w przyszłości](https://trello.com/c/eUMsMlJI/124-chore-ko%C5%84c%C3%B3wka-do-tworzenia-przyk%C5%82adowej-wizyty-w-przysz%C5%82o%C5%9Bci)

2024-07-22 21:26 UTC, linewelder commented
Zrobiłem rebase na dev

2024-07-23 10:15 UTC, linewelder requested changes

2024-07-23 10:15 UTC, linewelder commented on Api/Services/DebugService.cs
> +        );
daj jeszcze na koniec OrThrow(), żeby wyłapywać błędy

2024-07-23 10:15 UTC, linewelder commented on Api/Services/DebugService.cs
> +        );
daj jeszcze na koniec OrThrow(), żeby wyłapywać błędy

2024-07-23 10:15 UTC, linewelder commented on Api/Services/DebugService.cs
> +                        MenuItemId = 0,
czy to zadziała? id w bazie danych zacznają się od 1

2024-07-23 11:09 UTC, skrapi2011 commented on Api/Services/DebugService.cs
> +    public async Task<Result<VisitSummaryVM>> AddFutureVisitAsync(User user)
Zmienione

2024-07-23 11:17 UTC, skrapi2011 commented on Api/Services/DebugService.cs
> +            user
zmienione

2024-07-24 19:48 UTC, merged