[FIX] Niepotrzebne ładowania kolekcji nawigacyjnych
Reservant-inc/reservant-backend pull request #149
Opened 2024-07-30 15:54 UTC by Bambi54

- usunięty niepotrzebny include w GetMyRestaurantsAsync()
- zmieniona metoda GetRestaurantByIdAsync()

2024-08-02 15:07 UTC, linewelder requested changes
Zmień też sprawdzenie uprawnień uczestników wątków

2024-08-14 17:03 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[REFACTOR] Niepotrzebne ładowania kolekcji nawigacyjnych](https://trello.com/c/S4fKjL7I/125-refactor-niepotrzebne-%C5%82adowania-kolekcji-nawigacyjnych)

2024-08-22 20:19 UTC, linewelder commented
na pewno kiedyś zmerguję obiecuję, ale na razie widzę problem z nowym komitem, nad którem musiałbym się zastanowić chwilę

2024-08-29 17:34 UTC, merged

2024-08-29 17:35 UTC, linewelder commented
🥳🍾🎉