[FEATURE] deliveries
Reservant-inc/reservant-backend pull request #168
Opened 2024-08-12 20:30 UTC by Bambi54

2024-08-12 20:30 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Końcówki dostaw](https://trello.com/c/GljPE9fJ/129-feature-ko%C5%84c%C3%B3wki-dostaw)

2024-08-15 18:39 UTC, linewelder requested changes
pobierz też komit który spushowałem, dodaje on adnotacji od dokumentacji kodów błędów

2024-08-15 18:39 UTC, linewelder commented on Api/Models/Dtos/Delivery/DeliveryVM.cs
> +    public string? UserId { get; set; } = null!;
wszystkie pola muszą być required żeby się nie zapominało je inicjować

2024-08-15 18:39 UTC, linewelder commented on Api/Models/Dtos/Ingredient/IngredientDeliveryVM.cs
> +    public DateTime? ExpiryDate { get; set; }
wszystkie pola muszą być required żeby się nie zapominało je inicjować

2024-08-15 18:39 UTC, linewelder commented on Api/Services/DeliveryService.cs
> +        }
końcówka nie sprawdza uprawnień użytkownika

2024-08-15 18:39 UTC, linewelder commented on Api/Services/DeliveryService.cs
> +            RestaurantId = request.RestaurantId,
końcówka nic nie robi z informacją o zamówionych składnikach

2024-08-15 18:39 UTC, linewelder commented on Api/Services/DeliveryService.cs
> +            .AnyAsync(e => e.EmployeeId == userId && e.DateUntil == null && e.RestaurantId == request.RestaurantId);
końcówka musi też być dostępna dla właściciela restauracji.

najlepiej przenieść sprawdzenie uprawnień do AuthorizationService (prawdopodobnie będziesz musiał pobrać ostatnie zmiany z deva)

2024-08-16 15:19 UTC, Bambi54 commented on Api/Services/DeliveryService.cs
> +        }
a nie wystarczy [Authorize(Roles = Roles.RestaurantBackdoorsEmployee)] w kontrolerze?

2024-08-22 19:29 UTC, linewelder commented
zamykam, bo zmergowałem, ale musiałem najpierw zmienić base branch. teraz już nie mogę go zmienić

2024-08-22 19:29 UTC, closed without merging