Implementing setting VerifierId says its argument dont exist
Reservant-inc/reservant-backend pull request #18
Opened 2024-04-11 07:45 UTC by DummSmartass

2024-04-11 10:44 UTC, Mroxny submitted a review, later dismissed

2024-04-15 21:26 UTC, linewelder requested changes

2024-04-15 21:26 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +    [HttpPost("{restaurantId:int}")]
ścieżka miała być /restaurants/{id:int}/verify
czyli `HttpPost("{restaurantId:int}/verify")`

2024-04-15 21:26 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +    [ProducesResponseType(200), ProducesResponseType(401)]
ma być `ProducesResponseType(404)` zamiast `ProducesResponseType(401)`,
bo ta końcówka nie zwraca 401

2024-04-15 21:26 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +        return NotFound(404);
ma być `NotFound()`,
bo `NotFound(404)` nadpisuje konwencjonalną odpowiedź i zwraca po prostu liczbę 404

2024-04-15 21:26 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +        public async Task<bool> setVerifierIdAsync(User user, int idRestaurant)
metody nazywamy z dużej litery (w c#)

2024-04-15 21:26 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +        public async Task<bool> setVerifierIdAsync(User user, int idRestaurant)
tu brakuje `[Authorize(Roles.CustomerSupportAgent)]`

na samej końcówce, bo kontroler będzie dostępny dla wszystkich

2024-04-15 21:26 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +            return Ok(result);
ma być `Ok()`,
bo zawsze i tak zwraca się `true`

2024-04-15 21:26 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +    public async Task<ActionResult> setVerifierId(int restaurantId)
metody nazywamy z dużej litery (w c#)

2024-04-15 21:26 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +
nie zapisujesz zmian za pomocą `await context.SaveChangesAsync()`

2024-04-17 15:48 UTC, merged