Created POST menu/int/items
Reservant-inc/reservant-backend pull request #24
Opened 2024-04-18 07:52 UTC by skrapi2011

Added POST menu-id-items that adds given list of menuIds to specific menu.

2024-04-18 07:55 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dodawanie menu itemów do menu](https://trello.com/c/0H6ot2z7/40-dodawanie-menu-item%C3%B3w-do-menu)

2024-04-18 09:42 UTC, Mroxny submitted a review, later dismissed

2024-04-22 22:36 UTC, linewelder requested changes

2024-04-22 22:36 UTC, linewelder commented on Api/Controllers/MenuController.cs
> +    [HttpPost("/menu/{id:int}/items")]
źle napisałem na trello, tu raczej ma być `/menus/{id:int}/items`

2024-04-22 22:36 UTC, linewelder commented on Api/Controllers/MenuController.cs
> +    [ProducesResponseType(201)]
my zwracamy nie 201 (Created) tyklo 200 (Ok)

2024-04-22 22:36 UTC, linewelder commented on Api/Controllers/MenuController.cs
> +    public async Task<ActionResult> AddToMenu(int id, AddItemsRequest request)
ma być `ActionResult<MenuVM>`

2024-04-23 07:27 UTC, skrapi2011 commented on Api/Controllers/MenuController.cs
> +    [HttpPost("/menu/{id:int}/items")]
zmienione

2024-04-23 07:28 UTC, skrapi2011 commented on Api/Controllers/MenuController.cs
> +    [ProducesResponseType(201)]
zmienione

2024-04-23 07:29 UTC, skrapi2011 commented on Api/Controllers/MenuController.cs
> +    public async Task<ActionResult> AddToMenu(int id, AddItemsRequest request)
zmienione

2024-04-23 19:19 UTC, linewelder requested changes

2024-04-23 19:19 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +        var allBelongToUser = menuItemsToAdd.All(mi => mi.Restaurant.Group.OwnerId == user.Id);
musimy sprawdzać czy `mi.RestaurantId == menuToUpdate.RestaurantId`, bo menu itemy mogą być używane tylko w ramach jednej restauracji

2024-04-23 22:27 UTC, linewelder approved these changes

2024-04-23 22:30 UTC, merged