[FEATURE] MichalW GET /ingredients/{ingredientId}/history
Reservant-inc/reservant-backend pull request #253
Opened 2024-10-13 17:38 UTC by skrapi2011

+ Added Endpoint GET /ingredients/{ingredientId}/history
+ Added example corrections for ingredient ID 1

2024-10-13 17:38 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] GET /ingredients/{ingredientId}/history](https://trello.com/c/PkY2eWRR/177-feature-get-ingredients-ingredientid-history)

2024-10-15 18:08 UTC, linewelder requested changes

2024-10-15 18:08 UTC, linewelder commented on Api/Services/IngredientsService.cs
> +        }
```suggestion
        var restaurantId = ingredient.MenuItems.First().MenuItem.RestaurantId;
```
brak menuitemów to błąd aplikacji

2024-10-15 18:08 UTC, linewelder commented on Api/Services/IngredientsService.cs
> +                PropertyName = nameof(ingredientId)
```suggestion
                PropertyName = null,
```
jak napisałeś w atrybucie

2024-10-15 18:08 UTC, linewelder commented on Api/Services/IngredientsService.cs
> +    [MethodErrorCodes<AuthorizationService>(nameof(AuthorizationService.VerifyRestaurantBackdoorAccess))]
```suggestion
    [MethodErrorCodes<AuthorizationService>(nameof(AuthorizationService.VerifyRestaurantBackdoorAccess))]
    [MethodErrorCodes(typeof(Utils), nameof(Utils.PaginateAsync))]
```

2024-10-17 14:53 UTC, linewelder commented
zmergowałem, ale zapomniałem zmienić target branch

2024-10-17 14:53 UTC, closed without merging