[FEATURE] MichalW Max Visit Time
Reservant-inc/reservant-backend pull request #263
Opened 2024-10-21 17:03 UTC by skrapi2011

+ Added MaxReservationDuration variable
+ Added validation for POST visits (calculated visit time >= 30min)
+ Added validators for MaxReservationDuration GreaterOrEqualTo(30)

2024-10-21 17:04 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Maksymalny czas rezerwacji](https://trello.com/c/wT8NwpNq/186-feature-maksymalny-czas-rezerwacji)

2024-10-23 22:58 UTC, linewelder requested changes

2024-10-23 22:58 UTC, linewelder commented on Api/Models/Restaurant.cs
> +    public required int MaxReservationDuration { get; set; }
Lepiej podpisać że to minuty
```suggestion
    public required int MaxReservationDurationMinutes { get; set; }
```

2024-10-23 22:58 UTC, linewelder commented on Api/Validators/Restaurants/CreateRestaurantRequestValidator.cs
> +            .GreaterThanOrEqualTo(30);
Mi się bardzo nie podoba to że to magiczna liczba, przenieś to proszę do konstanty w klasie Visit, coś w stylu MinReservationDurationMinutes

2024-10-23 22:58 UTC, linewelder commented on Api/Services/VisitService.cs
> +        }
Zapomniałeś o atrybutach ErrorCode

2024-10-23 22:58 UTC, linewelder commented on Api/Validators/Restaurants/RestaurantValidator.cs
> +            .GreaterThanOrEqualTo(30);
i tu użyj tej konstanty

2024-10-23 22:58 UTC, linewelder commented on Api/Validators/Restaurants/UpdateRestaurantRequestValidator.cs
> +            .GreaterThanOrEqualTo(30);
i tu użyj tej konstanty

2024-10-23 22:58 UTC, linewelder commented on Api/Services/VisitService.cs
> +        if (visitDuration.TotalMinutes < 30)
i tu użyj tej konstanty

2024-10-24 19:30 UTC, merged