feature_MichalT_added_alreadyVeryfied_as_return_of_verifyId
Reservant-inc/reservant-backend pull request #28
Opened 2024-04-18 11:19 UTC by DummSmartass

2024-04-18 12:15 UTC, Mroxny commented on Api/Services/RestaurantService.cs
> +
Czy napewno potrzebujemy tutaj aż dwóch zapytań do bazy danych?

2024-04-24 17:25 UTC, linewelder requested changes

2024-04-24 17:25 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +        public async Task<int> SetVerifierIdAsync(User user, int idRestaurant)
Lepiej jest zwracać enum niż int. Możesz stworzyć go wewnątrz tej klasy (`RestaurantService`)

2024-04-24 17:25 UTC, linewelder commented on Api/Services/RestaurantService.cs
>              .AnyAsync();
Możesz użyć `FirstOrDefaultAsync()`, wtedy będziesz mógł sprawdzić `VerifierId` bez robienia drugiego zapytania

2024-04-24 17:25 UTC, linewelder commented on Api/Services/RestaurantService.cs
>              await context
Oraz tu zamiast robić `ForEachAsync` będzie można zmienić `VerifierId` na zwróconej restauracji

2024-04-24 17:25 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +            .Where(r => r.VerifierId == user.Id)
Błędem jest kiedy `VerifierId` nie jest nullem, a nie tylko `user.Id`, bo nie chcemy pozwolić na nadpisanie weryfikacji od innych użytkowników

2024-04-25 11:12 UTC, Mroxny submitted a review, later dismissed

2024-04-28 14:31 UTC, linewelder approved these changes

2024-04-28 14:31 UTC, merged