[FEATURE] PUT-DELETE-my-restaurant-id
Reservant-inc/reservant-backend pull request #33
Opened 2024-04-20 20:29 UTC by skrapi2011

Added 2 endpoints:
- PUT my-restaurant-id
- DELETE my-restaurant-id

2024-04-20 20:29 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PUT /my-restaurants/{id:int}](https://trello.com/c/cifqiGj4/49-put-my-restaurants-idint)

2024-04-23 22:47 UTC, linewelder requested changes

2024-04-23 22:47 UTC, linewelder commented on Api/Controllers/MyRestaurantsController.cs
> +        [ProducesResponseType(404)]
My nie zwracamy 403 404, tylko 400

2024-04-23 22:47 UTC, linewelder commented on Api/Controllers/MyRestaurantsController.cs
> +        [ProducesResponseType(404)]
My nie zwracamy 403 404, tylko 400

2024-04-23 22:47 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +        }
Nie miałeś robić DELETE, bo to miał Michał G (a i tak robimy soft delete więc nic nie usuwamy pod spodem)

2024-04-23 22:47 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +                    restaurant.Tags.Add(tag);
wydaje mi się że można po prostu zrobić `restaurant.Tags = await context.RestaurantTags.Where(...).ToListAsync();`

i też wydaje mi się że ty tworzysz nowe RestaurantTagi, a my tego nie chcemy, chcemy tylko połączyć z istniejącymi

2024-04-24 06:57 UTC, skrapi2011 commented on Api/Services/RestaurantService.cs
> +                    restaurant.Tags.Add(tag);
Powinno byc ok

2024-04-24 16:03 UTC, linewelder approved these changes

2024-04-24 17:05 UTC, merged