M ichal t feat] get /restaurants/unverified
Reservant-inc/reservant-backend pull request #343
Opened 2024-12-02 02:06 UTC by DummSmartass

2024-12-02 22:58 UTC, linewelder requested changes

2024-12-02 22:58 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +    [HttpGet("unverified")]
nie masz atrybutów Authorize i MethodErrorCodes

2024-12-02 22:58 UTC, linewelder commented on Api/Controllers/RestaurantsController.cs
> +    /// Find unveryfied restaurants as BOk restaurants by different criteria
```suggestion
    /// Find unverified restaurants by different criteria
```

2024-12-02 22:58 UTC, linewelder commented on Api/Data/Seeding/WitcherRestaurantSeeder.cs
> +            VerifierId = null,
aj czemu zabrałeś biednemu wedźminowi weryfikacje :(

2024-12-02 22:58 UTC, linewelder commented on Api/Data/Seeding/UnverfiedrestaurantSeeder1.cs
> +            Location = geometryFactory.CreatePoint(new Coordinate(20.90990467467737, 52.397394571933175)),
zmień prosze lokalizacje i nazwę tym restauracjom, bo na razie mają taką samą nazwę i znajdują się w tym samym punkcie co i restauracja anonymusa

2024-12-02 22:58 UTC, linewelder commented on Api/Dtos/Restaurants/QueryFilters.cs
> +        return restaurants.Where(restaurant => allowArchived?true:restaurant.IsArchived && allowUnverifed?true:restaurant.VerifierId != null);
z tego chyba finalnie nie skorzystałeś, na pewno działa bez tego?

moim zdaniem lepiej by było nie zmieniać tej funkcji tylko dodać drugą i w serwisie warunkowo je aplikować:
```cs
if (switchToUnverified) 
{
    query = query.OnlyUnverifiedRestaurants();
}
else
{
    query = query.OnlyActiveRestaurants();
}

2024-12-03 08:34 UTC, DummSmartass commented on Api/Data/Seeding/WitcherRestaurantSeeder.cs
> +            VerifierId = null,
Sorawdzałem czy działa i nie odwróciłem po tym XD

2024-12-03 08:34 UTC, DummSmartass commented on Api/Data/Seeding/UnverfiedrestaurantSeeder1.cs
> +            Location = geometryFactory.CreatePoint(new Coordinate(20.90990467467737, 52.397394571933175)),
Ok

2024-12-03 08:35 UTC, DummSmartass commented on Api/Dtos/Restaurants/QueryFilters.cs
> +        return restaurants.Where(restaurant => allowArchived?true:restaurant.IsArchived && allowUnverifed?true:restaurant.VerifierId != null);
Zobacze co dam radę zrobić

2024-12-10 10:34 UTC, merged