Extracted Token Generation to AuthService and added Token Refresh
Reservant-inc/reservant-backend pull request #39
Opened 2024-04-21 22:13 UTC by Michal-Gi

2024-04-22 07:25 UTC, Mroxny submitted a review, later dismissed

2024-04-22 22:44 UTC, linewelder requested changes

2024-04-22 22:44 UTC, linewelder commented on Api/Controllers/AuthController.cs
> +    public async Task<ActionResult> RefreshToken() {
ta końcówka powinna być Authorize

2024-04-22 22:44 UTC, linewelder commented on Api/Controllers/AuthController.cs
> +    public async Task<ActionResult> RefreshToken() {
my zwracamy UserInfo, więc ma być ActionResult<UserInfo>

2024-04-22 22:44 UTC, linewelder commented on Api/Services/AuthService.cs
> +        public async Task<SecurityToken> GenerateSecurityToken(User user, UserManager<User> userManager, IOptions<JwtOptions> jwtOptions)
lepiej byłoby jakbyśmy dostawali userManager i jwtOptions z konstruktora (dependency injection)

2024-04-23 19:11 UTC, linewelder approved these changes

2024-04-23 19:14 UTC, merged