Logowanie i Wylogowywanie
Reservant-inc/reservant-backend pull request #4
Opened 2024-03-09 16:03 UTC by skrapi2011

Dodano: 
- końcówki /login, /logout
- DTO LoginRequest, UserInfo

2024-03-10 13:57 UTC, linewelder requested changes

2024-03-10 13:57 UTC, linewelder commented on Api/Controllers/AuthController.cs
> +        var result = await signInManager.PasswordSignInAsync(email, password, false, false);
Warto by było przyjmować coś w stylu bool RememberMe w LoginRequest i podawać to zamiast pierwszego false

2024-03-10 13:57 UTC, linewelder commented on Api/Controllers/AuthController.cs
> +    /// Login authorization
Warto by było chyba pisać że zwraca ciastko, bo Kuba prosił o to

2024-03-10 13:57 UTC, linewelder commented on Api/Controllers/AuthController.cs
> +    /// Logging User out
Warto by było chyba pisać że usuwa ciastko

2024-03-10 13:57 UTC, linewelder commented on Api/Models/Dtos/LoginRequest.cs
> +    public required string Password { get; init; }
Tu przyjmować RememberMe

2024-03-10 14:12 UTC, linewelder commented
![](https://github.trello.services/images/mini-trello-icon.png) [Końcówki logowania się](https://trello.com/c/DQGATQLj/9-ko%C5%84c%C3%B3wki-logowania-si%C4%99)

2024-03-11 17:21 UTC, Mroxny approved these changes

2024-03-11 19:53 UTC, linewelder approved these changes

2024-03-11 19:57 UTC, merged