[FEATURE] PUT menus-id
Reservant-inc/reservant-backend pull request #47
Opened 2024-04-25 18:06 UTC by skrapi2011

Added endpoint:
- PUT menus-id

2024-04-25 18:06 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PUT /menus/{id:int}](https://trello.com/c/qVSDE9Cy/56-put-menus-idint)

2024-04-28 19:00 UTC, linewelder requested changes

2024-04-28 19:00 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +            errors.Add(new ValidationResult($"User not permitted to edit menu with ID {menuId}.", [ nameof(menuId) ]));
to samo co wyżej ^^^

2024-04-30 14:29 UTC, linewelder approved these changes

2024-04-30 14:33 UTC, merged