[FEATURE] PUT /menu-items/{id:int}
Reservant-inc/reservant-backend pull request #51
Opened 2024-04-27 17:26 UTC by Bambi54

2024-04-27 17:28 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PUT /menu-items/{id:int}](https://trello.com/c/Nene8qCh/53-put-menu-items-idint)

2024-04-28 18:36 UTC, linewelder requested changes

2024-04-28 18:36 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +
warto też walidować sam model po zmodyfikowaniu

2024-04-28 18:36 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +            item.Name = request.Name;
trzeba dodać `.Trim()`

2024-04-28 18:40 UTC, linewelder requested changes

2024-04-28 18:40 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +            }
nie musimy walidować requesta bo jest walidowany automatycznie przez asp net

2024-05-02 22:28 UTC, linewelder approved these changes

2024-05-02 22:28 UTC, merged