[FEATURE] Menu Names
Reservant-inc/reservant-backend pull request #62
Opened 2024-05-04 12:28 UTC by skrapi2011

2024-05-04 12:35 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dodać nazwy dla menu](https://trello.com/c/8DxfpfWA/59-doda%C4%87-nazwy-dla-menu)

2024-05-05 21:06 UTC, linewelder requested changes

2024-05-05 21:06 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +            Name = req.Name,
trzeba trimować nazwę

2024-05-05 21:06 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +        menu.Name = request.Name;
trzeba trimowac nazwe

2024-05-08 12:34 UTC, linewelder approved these changes

2024-05-08 12:35 UTC, merged