added photo to MenuItem
Reservant-inc/reservant-backend pull request #66
Opened 2024-05-07 22:13 UTC by Dzwiedzi

2024-05-08 09:28 UTC, linewelder requested changes
zobacz jak obsługujemy pliki przy tworzeniu restauracji i pobieraniu restauracji

2024-05-08 09:28 UTC, linewelder commented on Api/Models/Dtos/MenuItem/MenuItemSummaryVM.cs
> +    public required string PhotoFileName { get; set; }
to nie file name tylko po prostu Photo

2024-05-08 09:28 UTC, linewelder commented on Api/Models/Dtos/MenuItem/MenuItemVM.cs
> +    public required string PhotoFileName { get; set; }
to nie file name tylko po prostu photo (bo zwracamy ścieżkę do pliku, nie tylko nazwę)

2024-05-08 09:28 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +                PhotoFileName = req.PhotoFileName
nie sprawdzasz nazwy, zobacz w CreateRestaurantAsync jak to trzeba zrobić

2024-05-08 09:28 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +            item.PhotoFileName = request.PhotoFileName;
nie sprawdzasz nazwy

2024-05-08 09:28 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +                    PhotoFileName = mi.PhotoFileName
zwracamy sciezke, nie nazwe

2024-05-08 09:28 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +                PhotoFileName = menuItem.PhotoFileName
zwracamy sciezke, nie nazwe

2024-05-08 09:28 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +                PhotoFileName = item.PhotoFileName
zwracamy sciezke, nie nazwe

2024-05-08 09:28 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +                PhotoFileName = item.PhotoFileName,
zwracamy sciezke, nie nazwe

2024-05-08 09:28 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +                PhotoFileName = mi.PhotoFileName
zwracamy sciezke, nie nazwe

2024-05-08 09:28 UTC, linewelder commented on Api/Services/RestaurantMenuService.cs
> +                PhotoFileName = mi.PhotoFileName,
zwracamy sciezke, nie nazwe

2024-05-08 09:28 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +                    PhotoFileName = i.PhotoFileName
zwracamy sciezke, nie nazwe

2024-05-13 09:05 UTC, linewelder requested changes

2024-05-13 09:05 UTC, linewelder commented on Api/libman.json
co to xd

2024-05-13 09:05 UTC, linewelder commented on Api/Services/MenuItemsService.cs
> +            result = await validationService.ValidateAsync(menuItem);
Nie ma walidatora dla MenuItem

2024-05-13 09:05 UTC, linewelder commented on Api/Services/MenuItemsService.cs
>              if (!ValidationUtils.TryValidate(item, errors))
Tu trzeba użyć nowej walidacji

2024-05-13 18:47 UTC, Dzwiedzi commented on Api/libman.json
XDDD, nie mam pojęcia

2024-05-16 20:41 UTC, merged