[FEATURE] Zwracać DTO w POST /my-restaurants i POST /my-restaurant-groups
Reservant-inc/reservant-backend pull request #95
Opened 2024-05-25 12:47 UTC by Bambi54

2024-05-25 12:48 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Zwracać DTO w POST /my-restaurants i POST /my-restaurant-groups](https://trello.com/c/TN38MzvD/80-zwraca%C4%87-dto-w-post-my-restaurants-i-post-my-restaurant-groups)

2024-05-25 13:31 UTC, linewelder requested changes

2024-05-25 13:31 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +                IdCard = restaurant.IdCardFileName,
trzeba zwracać nie FileName tylko uploadService.GetPathForFileName(...)

2024-05-25 13:31 UTC, linewelder commented on Api/Services/RestaurantService.cs
> +                Photos = restaurant.Photos.Select(p => p.PhotoFileName).ToList(),
tu też

2024-05-28 10:47 UTC, linewelder requested changes
nie pozmieniałeś tego wszędzie, wszędzie gdzie jest FileName trzeba zwracać GetPathForFileName

2024-05-29 14:53 UTC, linewelder approved these changes

2024-05-29 14:58 UTC, merged