[FEATURE] Restaurant Location
Reservant-inc/reservant-backend pull request #97
Opened 2024-05-25 20:53 UTC by skrapi2011

Dodano lokalizację do restauracji w postaci Punktu(x,y), gdzie:
+ x - Longitude
+ y - Latitude

Restauracja przechowuje punkt, natomiast VM zwracaja zmienne Longitude, Latitude (Myślałem też o zrobieniu klasy Location przechowującej te obie zmienne - jak git pomysł to piszcie w changes requested)

Użyte biblioteki:
+ `NetTopologySuite`
+ `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite`

2024-05-25 21:01 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Lokalizacja dla restauracji](https://trello.com/c/EGnFsJR5/87-lokalizacja-dla-restauracji)

2024-05-27 11:00 UTC, linewelder requested changes
Tak, myślę, że stworzenie klasy dla DTO to bardzo dobry pomysł

2024-05-27 11:09 UTC, skrapi2011 commented on Api/Data/DbSeeder.cs
Wyczytałem gdzieś że konstruktor przyjmuje najpierw dlugosc, potem szerokosc, jak zamienisz to bylaby warszawa XDD ale chyba faktycznie przyjmuje szerokosc,dlugosc bo taki standard jest

2024-05-27 11:17 UTC, skrapi2011 commented on Api/Data/DbSeeder.cs
Tak jak np. tu - https://stackoverflow.com/questions/57172968/how-to-seed-nettopologysuite-geometries-point-data-from-a-json-file-in-asp-net-c

Zakładamy, że X to długość, a Y to szerokość (czyli odwrotnie do stadardu szerokość,długość.

Jak wygooglujesz te kordy odwrotnie to będzie okej

2024-05-27 15:57 UTC, skrapi2011 commented on Api/Data/ApiDbContext.cs
> +            x => x.UseNetTopologySuite());
Zmienione

2024-05-29 14:57 UTC, linewelder submitted a review, later dismissed

2024-05-29 15:06 UTC, merged